// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZhfrHCJeWWSxpV97IJtr4zROzmaK078c',
    appId: '1:264997629994:web:991a32b945ed86e6d21353',
    messagingSenderId: '264997629994',
    projectId: 'death-chat-b3cf5',
    authDomain: 'death-chat-b3cf5.firebaseapp.com',
    storageBucket: 'death-chat-b3cf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkRCWjJsHqhCY0SOrKHb2rzGZIaSeKveI',
    appId: '1:264997629994:android:df0384e03111dc20d21353',
    messagingSenderId: '264997629994',
    projectId: 'death-chat-b3cf5',
    storageBucket: 'death-chat-b3cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwojfFeljSiLpCkA46KAv__CQhVEqucDQ',
    appId: '1:264997629994:ios:b90517690f49f630d21353',
    messagingSenderId: '264997629994',
    projectId: 'death-chat-b3cf5',
    storageBucket: 'death-chat-b3cf5.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwojfFeljSiLpCkA46KAv__CQhVEqucDQ',
    appId: '1:264997629994:ios:b90517690f49f630d21353',
    messagingSenderId: '264997629994',
    projectId: 'death-chat-b3cf5',
    storageBucket: 'death-chat-b3cf5.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZhfrHCJeWWSxpV97IJtr4zROzmaK078c',
    appId: '1:264997629994:web:271e2c47de074efbd21353',
    messagingSenderId: '264997629994',
    projectId: 'death-chat-b3cf5',
    authDomain: 'death-chat-b3cf5.firebaseapp.com',
    storageBucket: 'death-chat-b3cf5.firebasestorage.app',
  );
}
